# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataownercode', models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI')], max_length=6)),
                ('lineplanningnumber', models.CharField(max_length=10)),
                ('publiclinenumber', models.CharField(max_length=10)),
                ('headsign', models.CharField(max_length=100)),
                ('json_lines', models.TextField()),
            ],
            options={
                'verbose_name': 'Lijn',
                'verbose_name_plural': 'Lijninformatie',
            },
        ),
        migrations.AlterUniqueTogether(
            name='line',
            unique_together=set([('dataownercode', 'lineplanningnumber')]),
        ),
    ]
