# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 14:14
from __future__ import unicode_literals

import app.models
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='transportmode',
            field=django_enumfield.db.fields.EnumField(default=0, enum=app.models.TransportMode),
        ),
        migrations.AlterField(
            model_name='line',
            name='dataownercode',
            field=models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('VEO', 'Veolia (Trein)'), ('NOORD', 'Arriva (Trein)'), ('SYN', 'Syntus (Trein)'), ('BRENG', 'Breng (CXX, Trein)'), ('VALLEI', 'Valleilijn (CXX, Trein)'), ('DB', 'DB (NS, Trein)'), ('NSI', 'NS International (NS, Trein)'), ('NMBS', 'NMBS (NS, Trein)'), ('KEO', 'Keolis (Trein)')], max_length=6),
        ),
    ]
