# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20160626_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='ppt_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='ppt_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
