# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20160709_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='average_km_rate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='Maximum eenheden'),
        ),
        migrations.AddField(
            model_name='line',
            name='entrance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Opstaptarief'),
        ),
        migrations.AddField(
            model_name='line',
            name='maximum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Maximum eenheden'),
        ),
        migrations.AddField(
            model_name='line',
            name='rounding',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Afrondniveau'),
        ),
    ]
