# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20160716_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='lineplanningnumber',
            field=models.CharField(max_length=25),
        ),
    ]
