# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 11:20
from __future__ import unicode_literals

import app.models
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_line_transportmode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='agegroup',
        ),
        migrations.AddField(
            model_name='product',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.AgeGroup'),
        ),
        migrations.AlterField(
            model_name='line',
            name='transportmode',
            field=django_enumfield.db.fields.EnumField(default=0, enum=app.models.TransportMode),
        ),
        migrations.AlterField(
            model_name='weekdays',
            name='weekday',
            field=django_enumfield.db.fields.EnumField(default=0, enum=app.models.Weekday),
        ),
    ]
