# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160618_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quarter_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name=b'Prijs per kwartaal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.AgeGroup', verbose_name=b'Leeftijd'),
        ),
        migrations.AlterField(
            model_name='product',
            name='annual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name=b'Prijs per jaar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='month_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name=b'Prijs per maand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=64, verbose_name=b'Naam'),
        ),
    ]
