# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160618_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='annual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name=b'Jaar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='month_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name=b'Maand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quarter_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name=b'Kwartaal'),
        ),
        migrations.AlterField(
            model_name='productreduction',
            name='linegroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LineGroup', verbose_name=b'Lijnen'),
        ),
        migrations.AlterField(
            model_name='productreduction',
            name='reduction',
            field=models.IntegerField(verbose_name=b'Kortingspercentage'),
        ),
        migrations.AlterField(
            model_name='productreduction',
            name='temporaryavailability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TemporalAvailability', verbose_name=b'Kalender'),
        ),
    ]
