# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160625_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age',
            name='end_age',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='age',
            name='from_age',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='description',
            field=models.CharField(max_length=64, verbose_name=b'Omschrijving'),
        ),
        migrations.AlterField(
            model_name='linegroup',
            name='description',
            field=models.CharField(max_length=64, verbose_name=b'Omschrijving'),
        ),
        migrations.AlterField(
            model_name='productreduction',
            name='description',
            field=models.CharField(max_length=64, verbose_name=b'Omschrijving'),
        ),
    ]
