# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20160626_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linegroup',
            options={'ordering': ['description']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='temporalavailability',
            options={'ordering': ['description'], 'verbose_name_plural': 'Temporal Availabilities'},
        ),
        migrations.AddField(
            model_name='agegroup',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='linegroup',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='temporalavailability',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
