# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20160627_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporalavailability',
            name='description',
            field=models.CharField(max_length=64, verbose_name=b'Omschrijving'),
        ),
    ]
