# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import utils.enums


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20160703_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', django_enumfield.db.fields.EnumField(default=1, enum=utils.enums.PriceDuration, verbose_name=b'Duur')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name=b'Prijs')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='app.Product')),
            ],
            options={
                'ordering': ['duration'],
            },
        ),
        migrations.RenameField(
            model_name='productbearer',
            old_name='products',
            new_name='product'
        ),
        migrations.AlterField(
            model_name='productbearer',
            name='bearer',
            field=django_enumfield.db.fields.EnumField(default=0, enum=utils.enums.Bearers, verbose_name=b'Drager'),
        ),
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together=set([('product', 'duration')]),
        ),
    ]
