# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 15:41
from __future__ import unicode_literals

from django.db import migrations

from utils.enums import PriceDuration


def move_prices(apps, schema_editor):
    Product = apps.get_model("app", "Product")
    ProductPrice = apps.get_model("app", "ProductPrice")
    for product in Product.objects.all():
        if product.month_price:
            ProductPrice(product=product, duration=PriceDuration.MONTH, price=product.month_price).save()
        if product.quarter_price:
            ProductPrice(product=product, duration=PriceDuration.QUARTER, price=product.quarter_price).save()
        if product.annual_price:
            ProductPrice(product=product, duration=PriceDuration.YEAR, price=product.annual_price).save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20160703_1455'),
    ]

    operations = [
        migrations.RunPython(move_prices),
    ]
