# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20160703_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='annual_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='month_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quarter_price',
        ),
        migrations.AlterField(
            model_name='productbearer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bearers', to='app.Product'),
        ),
    ]
