# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_enumfield.db.fields
import utils.enums


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20160703_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Vanaf')),
                ('available_to', models.DateTimeField(blank=True, null=True, verbose_name=b'Tot en met')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductValidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validity_type', django_enumfield.db.fields.EnumField(default=1, enum=utils.enums.ValidityType, verbose_name=b'Type')),
                ('number', models.PositiveSmallIntegerField(verbose_name=b'Waarde')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validities', to='app.Product')),
            ],
        ),
    ]
