# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_productavailability_productvalidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.AgeGroup', verbose_name=b'Leeftijd'),
        )
    ]
