# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 18:56
from __future__ import unicode_literals

from django.db import migrations


def move_ages(apps, schema_editor):
    Product = apps.get_model("app", "Product")
    for product in Product.objects.all():
        if product.age_group:
            for price in product.prices.all():
                price.age_group = product.age_group
                price.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_productprice_age_group'),
    ]

    operations = [
        migrations.RunPython(move_ages),
    ]
