# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20160703_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='age_group',
        ),
    ]
