# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 19:32
from __future__ import unicode_literals

import app.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20160703_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='type',
            field=django_enumfield.db.fields.EnumField(default=1, enum=app.models.PatternType, verbose_name=b'Type'),
        ),
    ]
