# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_line_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='pattern',
            field=models.CharField(max_length=64, verbose_name=b'Patroon'),
        ),
    ]
