# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django_enumfield.db.fields
import utils.enums


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20160709_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='linegroup',
            name='ppt_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='linegroup',
            name='source',
            field=django_enumfield.db.fields.EnumField(default=1, enum=utils.enums.DataSource),
        ),
    ]
