# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20160709_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linegroup',
            name='ppt_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
