# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20160709_1824'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='line',
            unique_together=set([('linegroup', 'pattern')]),
        ),
    ]
