# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20160709_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='incomplete',
            field=models.BooleanField(default=True, verbose_name=b'Incompleet?'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_validated',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Laatste validatie'),
        ),
        migrations.AddField(
            model_name='product',
            name='validated',
            field=models.BooleanField(default=False, verbose_name=b'Gevalideerd?'),
        ),
    ]
