# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_productlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age',
            name='end_age',
            field=models.PositiveIntegerField(verbose_name=b'Tot en met'),
        ),
        migrations.AlterField(
            model_name='age',
            name='from_age',
            field=models.PositiveIntegerField(verbose_name=b'Van'),
        ),
    ]
