# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20160716_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductValidityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Vanaf')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name=b'Tot en met')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validity_periods', to='app.Product')),
            ],
        ),
    ]
