# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_productvalidityperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='identifier',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name=b'Productnummer'),
        ),
    ]
