# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import utils.enums


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_product_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductValidityRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', django_enumfield.db.fields.EnumField(default=10, enum=utils.enums.ValidityRule, verbose_name=b'Regel')),
                ('allowed', models.BooleanField(default=True, verbose_name=b'Toegestaan?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validity_rules', to='app.Product')),
            ],
        ),
    ]
