# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import phonenumber_field.modelfields
import utils.enums


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_productvalidityrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Naam')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name=b'Telefoon')),
                ('url', models.CharField(blank=True, max_length=256, null=True, verbose_name=b'Link')),
            ],
        ),
        migrations.AlterField(
            model_name='productvalidityrule',
            name='allowed',
            field=django_enumfield.db.fields.EnumField(default=1, enum=utils.enums.RuleAllowed, verbose_name=b'Toegestaan?'),
        ),
        migrations.AddField(
            model_name='productseller',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Seller', verbose_name=b'Verkoper'),
        ),
    ]
