# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20161218_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='code',
            field=models.CharField(default='', max_length=15, unique=True, verbose_name=b'Code'),
            preserve_default=False,
        ),
    ]
