# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 14:19
from __future__ import unicode_literals

from django.db import migrations
import django_enumfield.db.fields
import utils.enums


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_seller_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvalidityperiod',
            name='type',
            field=django_enumfield.db.fields.EnumField(default=1, enum=utils.enums.PatternType, verbose_name=b'Type'),
        ),
    ]
