# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_productvalidityperiod_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvalidityrule',
            old_name='type',
            new_name='rule',
        ),
    ]
