# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-18 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20161218_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvalidityrule',
            name='value',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
